import numpy as np
print("......Array....")
print("\n")
A=np.array([1,2,4,3,5,9])
print("Array=",A)
B= np.array([[5, 8], [3, 1]])
print("\n")
print("matrix1 =",B)
print("\ntype of matrix",type(B))
print("\n .........dimension........")

print("dimension of matrix A is",A.ndim)
print("dimension of matrix A is",B.ndim)

print("shape(A):",A.shape)
print("shape(B):",B.shape)

print("\n............ arrange...........")
A=np.arange(1,10)
print("A",A)

print("\n......basic arithmetic operation....")
matrix1=np.array([[3,3],[3,2]])
matrix2=np.array([[9,6],[6,8]])
print("\n matrix1:")
print(matrix1)
print("\n matrix2:")
print(matrix2)
a=np.add(matrix1,matrix2)
print("\nmatrix addition")
print(a)
a=np.multiply(matrix1,matrix2)
print("\nmatrix multiplication")
print(a)
a=np.subtract(matrix1,matrix2)
print("\nmatrix substraction")
print(a)

print("\n...........matrix dot and Transpose..........")
matrix1=np.array([[2,3],[5,6]])
matrix2=np.array([[7,3],[2,9]])
print("\n matrix1:")
print(matrix1)
print("\n matrix2:")
print(matrix2)
a=np.dot(matrix1,matrix2)
print("\nmatrix dot product")
print(a)
a=np.transpose(a)
print("\nmatrix transpose")
print(a)

print("\n ..........determinant.................")
matrix=np.array([[[2,4,5],[6,7,2],[5,3,2]]])
print("matrix",matrix)
det=np.linalg.det(matrix)
print("\n",det)
inv=np.linalg.inv(matrix)
print("\n",inv)

print("\n ...............indexing..........")
x=np.arange(3,10)
print(x)
print(x[5])
print(x[3]+x[5])
print(x[-1])

print("\n ...............slicing..........")
x=np.arange(3,10)
print(x)
print(x[4:5])
print(x[:4])
print(x[5:])

print("\n ...............reshaping..........")
x=np.arange(1,16)
print(x)
w=x.reshape(5,3)
print("after reshaping",w)

print("\n ...............search and sort.........")
x=np.array([1,3,2,4,6,8,7,9,5])
print(x)
r=np.where(x==7)
print("position of 3")
print(r)
print("sorted array",np.sort(x))

print("\n ...............identity .........")
x=np.identity(3,dtype=int)
print("identity matrix")
print(x)
y=np.ones([2,2],dtype=int)
print("ones")
print(y)
y=np.zeros([2,2],dtype=int)
print("zeros")
print(y)

print("\n ...............Random.........")
x = np.random.randint(100, size=(5))
print(x)
x=np.random.randint(100)
print(x)
x=np.random.rand(7)
print(x)
x=np.random.randint(0,100.6)
